###
GET http://localhost:4000/api/

###
POST http://localhost:4000/api/
Content-Type: application/json

{
  "name": "alejandro",
  "lastName": "carreño rodas"
}

### 
PUT  http://localhost:4000/api/8
Content-Type: application/json

{
  "name": "diego",
  "lastName" : "Banegas"
}

### 
DELETE http://localhost:4000/api/4
