###
GET http://localhost:3000/api/users

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Sebastian",
  "lastName": "Cespedes Rodas"
}

### 
PUT  http://localhost:3000/api/users/4
Content-Type: application/json

{
  "name": "diego",
  "lastName" : "Banegas"
}

### 
DELETE http://localhost:3000/api/users/4
